#!/bin/sh
#ddev-generated

## Description: Run mkdocs commands
## Usage: mkdocs [args]
## Example: "ddev mkdocs build"
## ExecRaw: true

if [ "$1" = "serve" ]; then
  echo "This does not work for mkdocs in ddev"
  exit 1
fi

mkdocs "${@}"
