#!/bin/sh
#ddev-generated
## Description: Run pa11y on given environment
## Usage: pa11y URL [Pa11y options]
## Example:\n- Run Pa11y on the default URL with no options:\n\n    ddev pa11y\n\n- Run Pa11y on a given URL\n\n    ddev pa11y https://example.com/page1\n\n- Run Pa11y in a given URL with a 500 milliseconds timeout:\n\n    ddev pa11y https://example.com/page2 -t 500\n\n- See all available Pa11y options:\n\n    ddev pa11y -h\n    ddev pa11y --help\n\nSee Pa11y documentation at https://github.com/pa11y/pa11y\n\nNOTE: Although [flags] is displayed in the `Usage` section, meaning DDEV flags, please do not use them as they will be also passed to Pa11y and may cause errors.
## ExecRaw: true


# Process parameters
url=""

# Check if first parameter is a URL (doesn't start with -)
if [ "$#" -gt 0 ] && [ "${1#-}" = "$1" ]; then
  url="$1"
  shift
fi

# If no URL is provided, assume "https://web" URL, the web container default hostname.
if [ -z "$url" ]; then
  printf "No URL passed, assuming 'https://web'\n"
  url="https://web"
fi


if [ -z "$*" ]; then
  args_string="no additional arguments"
else
  args_string="args: '$*'"
fi

printf "Running pa11y on URL: '%s' with %s\n\n" "$url" "$args_string"

# Run pa11y with the URL and remaining parameters
NODE_PATH="/app/node_modules/" /app/node_modules/.bin/pa11y -c /app/config/config.json "$url" "$@"
