#ddev-generated
site_name: Shopware DDEV - Documentation
theme: material
dev_addr: '0.0.0.0:8000'
nav:
  - Home: index.md
  - DDEV: ddev.md
  - DDEV Deep-Dive: ddevDeepDive.md
  - DDEV Add-Ons: ddevAddOns.md
  - DevOps: devOps.md