#ddev-generated
# Configurable Buggregator Server for DDEV
services:
  buggregator:
    container_name: ddev-${DDEV_SITENAME}-buggregator
    hostname: ${DDEV_SITENAME}-buggregator
    image: "${BUGGREGATOR_IMAGE:-ghcr.io/buggregator/server:latest}"
    expose:
      - "${BUGGREGATOR_HTTP_PORT:-8000}"
      - "${BUGGREGATOR_SMTP_PORT:-1025}"
      - "${BUGGREGATOR_VAR_DUMPER_PORT:-9912}"
      - "${BUGGREGATOR_MONOLOG_PORT:-9913}"
      - "${BUGGREGATOR_SENTRY_PORT:-9511}"
      - "${BUGGREGATOR_RAY_PORT:-23517}"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=${BUGGREGATOR_HTTP_PORT:-8000}:${BUGGREGATOR_HTTP_PORT:-8000},${BUGGREGATOR_SMTP_PORT:-1025}:${BUGGREGATOR_SMTP_PORT:-1025},${BUGGREGATOR_VAR_DUMPER_PORT:-9912}:${BUGGREGATOR_VAR_DUMPER_PORT:-9912},${BUGGREGATOR_MONOLOG_PORT:-9913}:${BUGGREGATOR_MONOLOG_PORT:-9913},${BUGGREGATOR_SENTRY_PORT:-9511}:${BUGGREGATOR_SENTRY_PORT:-9511},${BUGGREGATOR_RAY_PORT:-23517}:${BUGGREGATOR_RAY_PORT:-23517}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
    networks:
      - ddev_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BUGGREGATOR_HTTP_PORT:-8000}"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    depends_on:
      - buggregator
